/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica_2_enrique_tebalan.frontedP2;
import com.mycompany.practica_2_enrique_tebalan.frontedP2.pantallaMenuPrincipal;
import com.mycompany.practica_2_enrique_tebalan.frontedP2.menuReportes;
import com.mycompany.practica_2_enrique_tebalan.frontedP2.menuAcercaDe;
import com.mycompany.practica_2_enrique_tebalan.frontedP2.menuAyuda;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class menuBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form menuBienvenida
     */
    public menuBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comenzarPartida = new javax.swing.JButton();
        reportesMemoria = new javax.swing.JButton();
        acercaDeMemoria = new javax.swing.JButton();
        ayudaMemoria = new javax.swing.JButton();
        accionCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENID@ AL VIDEOJUEGO MEMORIA");

        comenzarPartida.setText("COMENZAR PARTIDA");
        comenzarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarPartidaActionPerformed(evt);
            }
        });

        reportesMemoria.setText("REPORTES");
        reportesMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesMemoriaActionPerformed(evt);
            }
        });

        acercaDeMemoria.setText("ACERCA DE");
        acercaDeMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeMemoriaActionPerformed(evt);
            }
        });

        ayudaMemoria.setText("AYUDA");
        ayudaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaMemoriaActionPerformed(evt);
            }
        });

        accionCerrar.setText("CERRAR");
        accionCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionCerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("MENU PRINCIPAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(accionCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(comenzarPartida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acercaDeMemoria)
                                    .addComponent(reportesMemoria)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(ayudaMemoria))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(comenzarPartida)
                .addGap(24, 24, 24)
                .addComponent(reportesMemoria)
                .addGap(21, 21, 21)
                .addComponent(acercaDeMemoria)
                .addGap(18, 18, 18)
                .addComponent(ayudaMemoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accionCerrar)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarPartidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //JOptionPane.showMessageDialog(null, "Este es un mensaje informativo.");
        pantallaMenuPrincipal menu2 = new pantallaMenuPrincipal();
        menu2.setLocationRelativeTo(null);
        menu2.setVisible(true);

   
    }//GEN-LAST:event_comenzarPartidaActionPerformed

    private void reportesMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesMemoriaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menuReportes menuReporte = new menuReportes();
        menuReporte.setLocationRelativeTo(null);
        menuReporte.setVisible(true);
    }//GEN-LAST:event_reportesMemoriaActionPerformed

    private void acercaDeMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeMemoriaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menuAcercaDe menuAcercaDeActual = new menuAcercaDe();
        menuAcercaDeActual.setLocationRelativeTo(null);
        menuAcercaDeActual.setVisible(true);
    }//GEN-LAST:event_acercaDeMemoriaActionPerformed

    private void ayudaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaMemoriaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menuAyuda menuAyudon = new menuAyuda();
        menuAyudon.setLocationRelativeTo(null);
        menuAyudon.setVisible(true);
    }//GEN-LAST:event_ayudaMemoriaActionPerformed

    private void accionCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionCerrarActionPerformed
        // TODO add your handling code here:
       int opcion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el juego?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION)
            {
            this.dispose();
            System.exit(0);
            }
    }//GEN-LAST:event_accionCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accionCerrar;
    private javax.swing.JButton acercaDeMemoria;
    private javax.swing.JButton ayudaMemoria;
    private javax.swing.JButton comenzarPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reportesMemoria;
    // End of variables declaration//GEN-END:variables
}
