/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica_2_enrique_tebalan.frontedP2;


import com.mycompany.practica_2_enrique_tebalan.frontedP2.menuBienvenida;
import backendP2.generadorTableros;
import com.mycompany.practica_2_enrique_tebalan.gestorArchivos;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.net.URL;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JFrame;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author DELL
 */
public class pantallaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form pantallaMenuPrincipal
     */
    
   // private static final String IMAGEN = "imagenesCartas/imagenesTotal/0.JPG";
   // private boolean active = false;
    
    public pantallaMenuPrincipal() {
        initComponents();
      // mostrarImagen();
        fecha();
        hora();
        minutos();
        segundos();
    }
    
    private void mostrarImagen()
    {
        /*String rutaImagen = "C:\\Users\\DELL\\OneDrive\\Documentos\\NetBeansProjects\\PRACTICA_2_ENRIQUE_TEBALAN\\src\\main\\java\\imagenesCartas\\linuxlogo.png";
        JLabel imagenLabel = new JLabel();
        ImageIcon imagenIcon = new ImageIcon(rutaImagen);
        imagenLabel.add(imagenLabel,BorderLayout.SOUTH);
        imagenLabel.setSize(600,400);
        imagenLabel.setIcon(imagenIcon);
        imagenLabel.setHorizontalAlignment(SwingConstants.RIGHT);
        getContentPane().add(imagenLabel);
        pack();*/
    }
    public String nombreJugador1T ="";
    public String nombreJugador2T ="";
    
    private String leerNombre1()
    {
        nombreJugador1T = nombreJugador1.getText();
        
       // nombreJugador2T= nombreJugador2.getText();
        
        if(nombreJugador1T.isEmpty())
        {
            JOptionPane.showMessageDialog(pantallaMenuPrincipal.this, "Por favor ingresa correctamente los datos");
        }else{
            JOptionPane.showMessageDialog(pantallaMenuPrincipal.this, "nombre uno ingresado correctamente");
        }
        
        return nombreJugador1T;
    }
    
    public String leerNombre2()
    {
        //nombreJugador1T = nombreJugador1.getText();
        
         nombreJugador2T= nombreJugador2.getText();
        
        if(nombreJugador2T.isEmpty())
        {
            JOptionPane.showMessageDialog(pantallaMenuPrincipal.this, "Por favor ingresa correctamente los datos");
        }else{
            JOptionPane.showMessageDialog(pantallaMenuPrincipal.this, "nombre dos ingresado correctamente");
        }
        
        return nombreJugador2T;
    }
    
    private String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
        
    }
    public int hora,minutos,segundos;
    
    private int hora(){ 
      Calendar calendario = new GregorianCalendar();
      hora= calendario.get(Calendar.HOUR_OF_DAY);
      minutos = calendario.get(Calendar.MINUTE);
      segundos = calendario.get(Calendar.SECOND);
      //lblhora.setText(hora + ":" + minutos + ":" + segundos);   
      return hora;
    }
    
    private int minutos()
    {
        Calendar calendario = new GregorianCalendar();
        minutos = calendario.get(Calendar.MINUTE);
        return minutos;
    }
    
    private int segundos()
    {
        Calendar calendario = new GregorianCalendar();
        segundos = calendario.get(Calendar.SECOND);
        return segundos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regresarMenuBienvenida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombreJugador1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nombreJugador2 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modoFacil = new javax.swing.JButton();
        modoNormal = new javax.swing.JButton();
        modoDificil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelPartida = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        accionGuardarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU PRINCIPAL");

        regresarMenuBienvenida.setText("REGRESAR");
        regresarMenuBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMenuBienvenidaActionPerformed(evt);
            }
        });

        jLabel2.setText("INGRESE NOMBRE DE JUGADOR 1:");

        jScrollPane1.setViewportView(nombreJugador1);

        jLabel3.setText("INGRESE NOMBRE DE JUGADOR 2:");

        jScrollPane2.setViewportView(nombreJugador2);

        jLabel4.setText("ELIJE DIFICULTAD DE JUEGO:");

        jLabel5.setText("¡COMIENZA LA PARTIDA!");

        modoFacil.setText("FACIL");
        modoFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoFacilActionPerformed(evt);
            }
        });

        modoNormal.setText("NORMAL");
        modoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoNormalActionPerformed(evt);
            }
        });

        modoDificil.setText("DIFICIL");
        modoDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoDificilActionPerformed(evt);
            }
        });

        jLabel7.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel8.setText("ES TURNO DEL JUGADOR:");

        jLabel9.setText("Puntaje Jugador1:");

        jLabel10.setText("Puntaje Jugador2:");

        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPartidaLayout = new javax.swing.GroupLayout(panelPartida);
        panelPartida.setLayout(panelPartidaLayout);
        panelPartidaLayout.setHorizontalGroup(
            panelPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        panelPartidaLayout.setVerticalGroup(
            panelPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(panelPartida);

        lblImage.setText("jLabel6");

        accionGuardarArchivo.setText("Guardar");
        accionGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionGuardarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regresarMenuBienvenida)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(accionGuardarArchivo)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modoFacil)
                                .addGap(18, 18, 18)
                                .addComponent(modoNormal)
                                .addGap(18, 18, 18)
                                .addComponent(modoDificil)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limpiar)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modoNormal)
                            .addComponent(modoDificil)
                            .addComponent(modoFacil)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(regresarMenuBienvenida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accionGuardarArchivo)
                        .addGap(15, 15, 15)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiar)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10)
                        .addGap(105, 105, 105)
                        .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblImage))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMenuBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMenuBienvenidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menuBienvenida menu1= new menuBienvenida();
        menu1.setLocationRelativeTo(null);
        menu1.setVisible(true);
        
    }//GEN-LAST:event_regresarMenuBienvenidaActionPerformed
    
    
    private void modoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoNormalActionPerformed
      
        leerNombre1();
        leerNombre2();
        generadorTableros eleccionTablero = new generadorTableros(panelPartida, 4, 5); //10 PAREJAS
      /* if (active) {
            lblImage.setIcon(null);
        } else {
            lblImage.setIcon(new ImageIcon(getClass().getClassLoader().getResource(IMAGEN)));
        }
        active = !active;*/
  
// TODO add your handling code here:
    }//GEN-LAST:event_modoNormalActionPerformed

    private void modoDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoDificilActionPerformed
        leerNombre1();
        leerNombre2();
        generadorTableros eleccionTablero = new generadorTableros(panelPartida, 6, 5); //15 PAREJAS
        // TODO add your handling code here:
    }//GEN-LAST:event_modoDificilActionPerformed

    private void modoFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoFacilActionPerformed
        leerNombre1();
        leerNombre2();
        generadorTableros eleccionTablero = new generadorTableros(panelPartida, 2, 5); //5 PAREJAS
        // TODO add your handling code here:
    }//GEN-LAST:event_modoFacilActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        panelPartida.removeAll();
        panelPartida.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    private void accionGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionGuardarArchivoActionPerformed
       int hora = hora();
       int minutos = minutos();
       int segundos = segundos();
        gestorArchivos archivo = new gestorArchivos();
        archivo.conectarConCarpeta();
        archivo.escribirEnArchivoDeTexto("NOMBRE JUGADOR 1:"+nombreJugador1T+"\n");
        archivo.escribirEnArchivoDeTexto("NOMBRE JUGADOR 2:"+nombreJugador2T+"\n");
        //archivo.escribirEnArchivoDeTexto(formatofecha.format(fecha));
        archivo.escribirEnArchivoDeTexto("Hora: " + hora+"\n");
        archivo.escribirEnArchivoDeTexto("Minutos: " + minutos+"\n");
        archivo.escribirEnArchivoDeTexto("Segundos: " + segundos+"\n");
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaFormateada = formatofecha.format(new Date());
        archivo.escribirEnArchivoDeTexto("Fecha: " + fechaFormateada+"\n");
        archivo.escribirEnArchivoDeTexto("-------------------------------------------------------------");
        //archivo.escribirEnArchivoDeTexto(formatofecha.format(fecha));
        //archivo.escribirEnArchivoDeTexto(hora);
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_accionGuardarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaMenuPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accionGuardarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modoDificil;
    private javax.swing.JButton modoFacil;
    private javax.swing.JButton modoNormal;
    private javax.swing.JTextPane nombreJugador1;
    private javax.swing.JTextPane nombreJugador2;
    private javax.swing.JPanel panelPartida;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JButton regresarMenuBienvenida;
    // End of variables declaration//GEN-END:variables
}
